# Generated by Django 4.1.2 on 2022-10-11 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 21, 27, 25, 887037, tzinfo=datetime.timezone.utc), verbose_name='date_published'),
        ),
    ]
